### PR TITLE
Clarify the relation between SQLiteContentProviderImpl and ExtendedSQLiteOpenHelper

### LINKED ISSUE #57: getDatabaseHelper(Context context) has incorrect declaration.
SQLiteContentProviderImpl has the following implementation of getDatabaseHelper():

```
@Override
protected SQLiteOpenHelper getDatabaseHelper(Context context) {
    try {
        return new ExtendedSQLiteOpenHelper(context, getCursorFactory());
    } catch (IOException e) {
        Log.Provider.e(e);
        throw new IllegalStateException(e.getMessage());
    }
}
```

It looks like I can redefine this function and return my own SQLiteOpenHelper. But it doesn't work: somewhere in the lib will be casting back to ExtendedSQLiteOpenHelper:

Caused by: java.lang.ClassCastException: ru.jollydroid.app.Db cannot be cast to novoda.lib.sqliteprovider.sqlite.ExtendedSQLiteOpenHelper
at novoda.lib.sqliteprovider.provider.SQLiteContentProviderImpl.onCreate(SQLiteContentProviderImpl.java:43)
at android.content.ContentProvider.attachInfo(ContentProvider.java:1748)

I think you need to split ExtendedSQLiteOpenHelper to two classes. One with common helper functions like getColumns() and getTables, and one with implementation of your helper.

### PR DESCRIPTION
**Pull request by friedger**
This PR clarifies the need of SQLiteContentProviderImpl for an ExtendedSQLiteOpenHelper.

getDatabaseHelper is overwritten and returns the ExtendedSQLiteOpenHelper.

### CODE REVIEW

**Comment by stefanhoth** [comment]
Can one of the admins review this PR?

**Comment by frapontillo** [comment]
CI, please test this.

**Comment by friedger** [comment]
And it forces sub classes to also use the ExtendedSQLiteOpenHelper.

**Comment by juankysoriano** [comment]
@friedger you mention that this fixes #57, correct me if I am wrong but seems that rather than fixing formalises the expected usage, right? The person opening that issue wanted to use his own `SQLiteOpenHelper`, your PR instead makes explicit the need for `ExtendedSQLiteOpenHelper`; am I right?

**Comment by blundell** [comment]
I agree with @juankysoriano 

> And it forces sub classes to also use the ExtendedSQLiteOpenHelper.

we don't want to force this do we? Rather we should get rid of the explicit cast and code that class to the interface

**Comment by friedger** [comment]
I have removed the reference to #57 . So, this does not fix it, but helps users to understand the implementation better.

**Comment by blundell** [comment]
If we merged this solution it would couple us tighter to the current implementation. 

Right now it is an implicit cast that the public API doesn't know about. Merging this change would make the contract explicit but it would also mean a non backwards compatible change i.e. compile errors when people upgrade - then if we did the fix for #57 we would change the signatures back and people would again have a break in the API contract.

I don't think we should merge this change.

Sorry 👍

**Pull request closed without merging**
